apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: aspnetapp-pvc-green
  namespace: prod
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aspnetapp-green
  namespace: prod
spec:
  replicas: 3
  selector:
    matchLabels:
      app: aspnetapp-green
  template:
    metadata:
      labels:
        app: aspnetapp-green
    spec:
      containers:
        - name: aspnetapp
          image: inlogik.azurecr.io/aspnetapp:green-latest
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
          volumeMounts:
            - name: storage
              mountPath: /var/aspnetapp/data

          livenessProbe:
            httpGet:
              path: /healthz
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 20

          readinessProbe:
            httpGet:
              path: /ready
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: aspnetapp-pvc-green
      imagePullSecrets:
        - name: acr-secret

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: aspnetapp-green-hpa
  namespace: prod
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: aspnetapp-green
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
