name: Pull and Push to ACR
env:
    AZURE_CONTAINER_REGISTRY: "inlogik.azurecr.io"


on:
  push:
    branches:
      - main

jobs:
  pull-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ env.AZURE_CONTAINER_REGISTRY }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Pull, Tag and Push Docker image
      run: |
        docker pull mcr.microsoft.com/dotnet/samples:aspnetapp
        docker tag mcr.microsoft.com/dotnet/samples:aspnetapp ${{env.AZURE_CONTAINER_REGISTRY}}/aspnetapp:${{ github.sha }}
        docker push ${{env.AZURE_CONTAINER_REGISTRY}}/aspnetapp:${{ github.sha }}
